
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi

CIRQUE_PINNACLE_ATTENUATION = ADC_ATTENUATE_4X # down to 1X
CIRQUE_PINNACLE_TAPPING_TERM = 200

# CIRQUE_PINNACLE_TOUCH_DEBOUNCE = default unclear
POINTING_DEVICE_TASK_THROTTLE_MS = 10 # maybe lower?
