#pragma once


#define COMBO_TERM 40
#define COMBO_TERM_PER_COMBO
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_VARIABLE_LEN



#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM 160
//#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD
#define BILATERAL_COMBINATIONS 300
//#define CIRQUE_PINNACLE_TAP_ENABLE

#define MOUSE_EXTENDED_REPORT
